participants:
  - el_type: geth
    cl_type: lodestar
    cl_image: chainsafe/lodestar:kurtosis-ci
  - el_type: geth
    cl_type: lighthouse
additional_services:
  - assertoor
assertoor_params:
  run_block_proposal_check: true
  run_transaction_test: true
  run_blob_transaction_test: true
  run_opcodes_transaction_test: true
