name: Check docs

on:
  push:
    # We intentionally don't run push on feature branches. See PR for rational.
    branches: [unstable, stable]
  pull_request:

jobs:
  build:
    name: Docs spellcheck
    runs-on: ubuntu-latest
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup-and-build"
        with:
          node: 24

      - name: Check wordlist is sorted
        run: scripts/wordlist_sort_check.sh

      - name: Build and collect docs
        run: pnpm docs:build

      # Run prettier check after generating the docs
      - name: Check docs format
        run: pnpm docs:lint

      # Run spellcheck AFTER building docs, in case the CLI reference has issues
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.32.0
