name: Sim merge execution/builder tests

concurrency:
  # If PR, cancel prev commits. head_ref = source branch name on pull_request, null if push
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    # We intentionally don't run push on feature branches. See PR for rational.
    branches: [unstable, stable]
  pull_request:
  workflow_dispatch:

env:
  GETH_IMAGE: ethereum/client-go:v1.10.25
  NETHERMIND_IMAGE: nethermind/nethermind:1.14.3
  MERGEMOCK_IMAGE: g11tech/mergemock:latest
  GETH_WITHDRAWALS_IMAGE: g11tech/geth:withdrawalsfeb8
  ETHEREUMJS_WITHDRAWALS_IMAGE: g11tech/ethereumjs:blobs-b6b63
  NETHERMIND_WITHDRAWALS_IMAGE: nethermindeth/nethermind:withdrawals_yolo
  ETHEREUMJS_BLOBS_IMAGE: g11tech/ethereumjs:blobs-b6b63

jobs:
  sim-merge-tests:
    name: Sim merge tests
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup-and-build"
        with:
          node: 24

      - name: Pull Geth
        run: docker pull $GETH_IMAGE

      - name: Pull Nethermind
        run: docker pull $NETHERMIND_IMAGE

      - name: Pull mergemock
        run: docker pull $MERGEMOCK_IMAGE

      - name: Test Lodestar <> mergemock relay
        run: yarn test:sim:mergemock
        working-directory: packages/beacon-node
        env:
          EL_BINARY_DIR: ${{ env.MERGEMOCK_IMAGE }}
          EL_SCRIPT_DIR: mergemock
          LODESTAR_PRESET: mainnet
          ENGINE_PORT: 8551
          ETH_PORT: 8661

      - name: Upload debug log test files
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: debug-test-logs
          path: packages/beacon-node/test-logs
